import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar/Navbar";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";

const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fira_code.className} antialiased`}>
        <Navbar />
        <ThemeProvider attribute="class" defaultTheme="dark">
          {/* <MaxWidthWrapper> */}
          <div className="flex-grow flex-1">{children}</div>
          {/* </MaxWidthWrapper> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
